[env:esp32]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_speed = 921600
upload_port = COM5
lib_deps =
    knolleary/PubSubClient@^2.8
build_flags =
    -D PSTR_EXPAND=1